# gitops-platform/services/base/service-template/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{SERVICE_NAME}}-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{SERVICE_NAME}}-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi