# gitops-platform/services/base/service-template/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-placeholder-static-pvc
spec:
  accessModes:
    - ReadWriteOnce  # ← Changed from ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-placeholder-media-pvc
spec:
  accessModes:
    - ReadWriteOnce  # ← Changed from ReadWriteMany
  resources:
    requests:
      storage: 10Gi