# gitops-platform/services/wallet-service/base/secrets/wallet-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wallet-secrets
  labels:
    app: wallet
    app.kubernetes.io/component: wallet-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: "django-insecure-$mlx&v1w@t&d#=c@k76%c9qp+2frp*i_q&7cdj!wiuey90$e0y"
  # DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,wallet-service,wallet-service.wallet-service.svc.cluster.local"
  DJANGO_DEBUG: "False"
  
  # Auth & Security
  INTERNAL_API_KEY: "super-secret-internal-key-change-in-prod"
  SERVICE_JWT: "my_jwt_secret_123!"
  JWT_SECRET: "my_jwt_secret_123!"