# gitops-platform/services/wallet-service/base/wallet-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-service-sa
  namespace: wallet-service
  labels:
    app: wallet-service
    managed-by: gitops
    component: wallet-service