# gitops-platform/infrastructure/base/secrets/postgres-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: infrastructure
  labels:
    app: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: ishimwe
  POSTGRES_PASSWORD: "2025New+"
  # Infrastructure PostgreSQL (platform level)
  POSTGRES_DB: platform
  # Auth service database
  AUTH_POSTGRES_DB: authdb
  AUTH_POSTGRES_USER: ishimwe
  AUTH_POSTGRES_PASSWORD: "2025New+"
  # Payment service database
  PAYMENT_POSTGRES_DB: paymentdb
  PAYMENT_POSTGRES_USER: ishimwe
  PAYMENT_POSTGRES_PASSWORD: "2025New+"