# infrastructure/base/secrets/postgres-credentials.yaml (single source)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: ishimwe
  POSTGRES_PASSWORD: "2025New+"
  # Use placeholders or let each overlay override what it needs
  DB_NAME: $(DB_NAME)
  DB_USER: $(DB_USER)
  DB_PASSWORD: $(DB_PASSWORD)