# gitops-platform/infrastructure/base/secrets/redis-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  labels:
    app: redis
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: "dev-redis-password"