# gitops-platform/services/room-service/base/room-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: room-service-sa
  namespace: room-service
  labels:
    app: room-service
    managed-by: gitops
    component: room-service