# gitops-platform/services/room-service/base/secrets/room-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: room-secrets
  labels:
    app: room
    app.kubernetes.io/component: room-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: "django-insecure-$plx&v1w@t&d#=c@k76%c9qp+2frp*i_q&7vxj@wiuey60$e0d"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,room-service,room-service.room-service.svc.cluster.local"
  DJANGO_DEBUG: "False"
  
  # Auth & Security
  INTERNAL_API_KEY: "super-secret-internal-key-change-in-prod"
  SERVICE_JWT: "my_jwt_secret_123!"