apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: post-ingress
  namespace: post-service
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/service.headers: |
      customrequestheaders:
        Host: post-service.post-service.svc.cluster.local
spec:
  rules:
  - host: post.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: post-service
            port:
              number: 8080