apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres/secret.yaml
- postgres/statefulset.yaml
- postgres/service.yaml
- redis/secret.yaml
- redis/configmap.yaml
- redis/statefulset.yaml
- redis/service.yaml
- rabbitmq/secret.yaml
- rabbitmq/configmap.yaml
- rabbitmq/statefulset.yaml
- rabbitmq/service.yaml
- kafka/namespace.yaml
- kafka/operator.yaml
- kafka/kafka-cluster.yaml
- traefik/  # Helm chart

labels:
- pairs:
    managed-by: gitops
  includeSelectors: false