# services/frontend/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service-template
  - frontend-sa.yaml

images:
  - name: placeholder
    newName: alphaxad9/booking_microservice_frontend
    newTag: "0.0.1"

patches:
  # Patch deployment name and references
  - target:
      kind: Deployment
      name: service-placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
      - op: replace
        path: /metadata/labels/app
        value: frontend
      - op: replace
        path: /metadata/labels/service
        value: frontend
      - op: replace
        path: /spec/selector/matchLabels/app
        value: frontend
      - op: replace
        path: /spec/template/metadata/labels/app
        value: frontend
      - op: replace
        path: /spec/template/metadata/labels/service
        value: frontend
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: frontend-sa
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: frontend

  # Patch service name
  - target:
      kind: Service
      name: service-placeholder-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
      - op: replace
        path: /metadata/labels/app
        value: frontend
      - op: replace
        path: /spec/selector/app
        value: frontend