apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

generatorOptions:
  disableNameSuffixHash: true

resources:
  - api-deployment.yaml
  - service.yaml
  - frontend-ingress.yaml
  - frontend-sa.yaml

configMapGenerator:
  - name: frontend-config
    literals:
      - REACT_APP_API_BASE_URL=http://auth.local/zedvye_one/
      - REACT_APP_ROOM_SERVICE_URL=http://room.local/room_service/
      - REACT_APP_BOOKING_SERVICE_URL=http://booking.local/booking_service/booking/
      - REACT_APP_POSTS_SERVICE_URL=http://post.local/api/v1/
      - REACT_APP_WALLET_SERVICE_URL=http://wallet.local/wallet_service/
      - NODE_ENV=production

secretGenerator:
  - name: frontend-secrets
    literals:
      - API_KEY=change-me-in-production

images:
  - name: alphaxad9/booking_microservice_frontend
    newTag: "0.0.4"