# services/wallet-service/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallet-service

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
      managed-by: gitops
    includeSelectors: false
    
configMapGenerator:
  - name: wallet-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - DJANGO_DEBUG=True
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://localhost:8001
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://localhost:8001
      - CORS_ALLOW_CREDENTIALS=True

patches:
  # Set replicas for all deployments in dev
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: wallet-api
  
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: wallet-rabbitmq-consumer
  
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: wallet-producer