apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-rewrite
  namespace: infrastructure
  labels:
    app: traefik
    managed-by: gitops
spec:
  replacePathRegex:
    regex: ^/api/auth/(.*)
    replacement: /zedvye_one/$1