apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: booking-rewrite
  namespace: infrastructure
  labels:
    app: traefik
    managed-by: gitops
spec:
  replacePathRegex:
    regex: ^/api/booking/(.*)
    replacement: /booking_service/booking/$1