apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: post-rewrite
  namespace: infrastructure
  labels:
    app: traefik
    managed-by: gitops
spec:
  replacePathRegex:
    regex: ^/api/post/(.*)
    replacement: /api/v1/$1