apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: infrastructure
  labels:
    app: postgres
    managed-by: gitops
type: Opaque
stringData:
  POSTGRES_USER: ishimwe
  POSTGRES_PASSWORD: "2025New+"
  POSTGRES_DB: postgres
  # For applications (actual values, not placeholders)
  DB_NAME: postgres
  DB_USER: ishimwe
  DB_PASSWORD: "2025New+"