# services/auth-service/base/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi