# gitops-platform/services/booking-service/base/secrets/booking-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: booking-secrets
  labels:
    app: booking
    app.kubernetes.io/component: booking-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: "django-insecure-$mlx&v1w@t&d#=c@k76%c9qp+2frp*i_q&7vxj@wiuey60$e0y"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,booking-service,booking-service.booking-service.svc.cluster.local"
  DJANGO_DEBUG: "False"
  
  # Auth & Security
  INTERNAL_API_KEY: "super-secret-internal-key-change-in-prod"
  SERVICE_JWT: "my_jwt_secret_123!"