apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: infrastructure
  labels:
    managed-by: gitops
spec:
  kafka:
    replicas: 1
    version: 4.1.1
    image: apache/kafka:4.1.1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
    image: apache/kafka:4.1.1  
  entityOperator:
    topicOperator: {}
    userOperator: {}