apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: kafka-operator
  labels:
    app: strimzi
    app.kubernetes.io/name: strimzi-cluster-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: strimzi-cluster-operator
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: strimzi-cluster-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: kafka
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: quay.io/strimzi/operator:0.38.0
        command:
          - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          value: "*"
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        - name: STRIMZI_FEATURE_GATES
          value: +UseKRaft
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"