apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: post-service

resources:
  - ../../base

labels:
  - pairs:
      environment: prod
      managed-by: gitops
    includeSelectors: false
    
configMapGenerator:
  - name: post-config
    behavior: merge
    literals:
      - LOG_LEVEL=WARN
      - GIN_MODE=release
      - FRONTEND_URL=https://example.com
      - AUTH_PUBLIC_KEY_URL=http://auth-service:8000/zedvye_one/users/public_key/
      - AUTH_SERVICE_URL=http://auth-service:8000/zedvye_one
      - KAFKA_BROKERS=kafka-prod-1:9092,kafka-prod-2:9092,kafka-prod-3:9092
      - KAFKA_TOPIC=microservice_one.events
      - KAFKA_GROUP_ID=post_service_outbox_publisher
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ENABLE_AUTO_COMMIT=false
      - KAFKA_AUTO_OFFSET_RESET=earliest
      - KAFKA_RETRIES=5
      - KAFKA_POLL_TIMEOUT=1.0
      - POSTGRES_HOST=postgres-prod
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgresgo1
      - POSTGRES_USER=ishimwe
      - PORT=8080
      - AUTH_PUBLIC_KEY_TTL=300

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment