# services/room-service/base/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: room-service-static-pvc
  labels:
    app: room-service
    managed-by: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: room-service-media-pvc
  labels:
    app: room-service
    managed-by: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi