apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
spec:
  encryptedData:
    password: AgBkY...  # Generated via kubeseal
  template:
    metadata:
      name: postgres-credentials
    type: Opaque